### ISSUE TITLE
Please clarify license

### ISSUE THREAD

**Issue by markxnelson** [siebenmann/go-kstat#1]
Hi, 
Thank you for creating this.  I would like to use this as a dependency, but I need to ask you to clarify the licensing please.  I cannot find any indication of what type of license this code is offered under.  Would you consider adding a license to the repository please?
Thanks for your help,
Mark

**Comment by siebenmann** [comment]
I've updated things to clarify the license. Thanks for bringing this up and sorry for the delay.

Also, as a disclaimer, we don't have Illumos/Solaris machines any more so I'm no longer in a position to make updates or fix bugs on my own, although I would be happy to accept pull requests if you find anything in your use of the package. I think everything works fine (it did for us when we had Illumos machines), but I can no longer be sure or do anything about it.
