### ISSUE TITLE
Maintain go-kstat

### ISSUE THREAD

**Issue by cneira** [siebenmann/go-kstat#2]
Hello @siebenmann 
Along with @Smithx10 we are working porting nomad to illumos and go-kstat will make things easier for us, we would like to continue working on this package. Would you be willing to transfer the ownership of this repo to illumos organization?

**Comment by jclulow** [comment]
We're certainly prepared to accept the repository, move it into the illumos organisation, and then maintain it within the community if you'd like to do that.

**Comment by Smithx10** [comment]
@jclulow  @jclulow  @siebenmann,  Definitely interested in moving this into the org!

**Comment by siebenmann** [comment]
I would be happy to see this move to Illumos's hands and keep living on and being useful to people there. I've never done such a transfer in Github before, so I may need some advice on how best to do it.

**Comment by jclulow** [comment]
Great!  I believe in order to effect a transfer, one GitHub account requires administrative permission over the repository to move, as well as permission to create a repository in the target organisation.  I have the latter, so if you can grant me the former then I will try to move it!

**Comment by jclulow** [comment]
Hi, @siebenmann! Someone asked me about this again today and I realised I had been busy with other things and had forgotten to follow up.  Would you be able to grant me administrative access to this repository so that I can move it into the illumos organisation?

**Comment by siebenmann** [comment]
If I'm reading Github's documentation correctly, specifically [this page](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository), I think the process I need to do is transfer the repository to you, which will let you move it into the Illumos organization. Is this right as far as you know or is there another process/web page/etc I should consult?

**Comment by jclulow** [comment]
I suspect it would be better to move it directly from your account to the illumos organisation.  If it takes a detour through my account, I don't know if GitHub will continue to redirect people from this URL straight over to the new eventual URL under illumos.

If you add me as a collaborator on this repository, with the **Admin** access level, I believe I can begin the transfer myself -- and I have access to create repositories under illumos, so it should all just work.

**Comment by siebenmann** [comment]
I've sent the invite now, and I think I can only make you an admin once you're a collaborator (or at least I didn't see an access level option on the invite).

**Comment by siebenmann** [comment]
I don't think I can make you an Admin of a personal repository. I don't see any option for it, and [the Github documentation on permission levels for personal repos](https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/permission-levels-for-a-user-account-repository) doesn't list it as a possibility.

**Comment by siebenmann** [comment]
Github doesn't immediately disallow an attempt to transfer the repo to 'illumos', although I did not go ahead and click the button to actually start the transfer (which might have made it error out). I can try to go through with that in case it works, or I can transfer it to you; let me know.

**Comment by jclulow** [comment]
You're right -- my apologies, most of my GitHub permissions experience is with organisations.  If you push the button on a transfer to illumos and that appears to work, that'd be great; otherwise, transfer it to me and I'll transfer it over again.  Sorry for the bother!

**Comment by siebenmann** [comment]
The transfer to illumos failed with an 'I don't have permission to create repos in illumos' error, which I sort of expected, so I'm now transferring it to you.

**Comment by jclulow** [comment]
Transfer to illumos is now complete.  Thanks, @siebenmann!
